//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommandXmlConverter.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CommandXmlConverter.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   フォルダの変更 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string GroupName_ChangeDir {
            get {
                return ResourceManager.GetString("GroupName_ChangeDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   コマンド実行 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string GroupName_Command {
            get {
                return ResourceManager.GetString("GroupName_Command", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイル一覧 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string GroupName_FileList {
            get {
                return ResourceManager.GetString("GroupName_FileList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイル操作 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string GroupName_FileOperation {
            get {
                return ResourceManager.GetString("GroupName_FileOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイル操作(その他) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string GroupName_FileOperationEtc {
            get {
                return ResourceManager.GetString("GroupName_FileOperationEtc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   カーソル移動 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string GroupName_MoveCursor {
            get {
                return ResourceManager.GetString("GroupName_MoveCursor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   開く に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string GroupName_Open {
            get {
                return ResourceManager.GetString("GroupName_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   設定変更 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string GroupName_Setting {
            get {
                return ResourceManager.GetString("GroupName_Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SSH に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string GroupName_SSH {
            get {
                return ResourceManager.GetString("GroupName_SSH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ツール に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string GroupName_Tools {
            get {
                return ResourceManager.GetString("GroupName_Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ウィンドウ操作 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string GroupName_Window {
            get {
                return ResourceManager.GetString("GroupName_Window", resourceCulture);
            }
        }
        
        /// <summary>
        ///   編集 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string VGroupName_G_Edit {
            get {
                return ResourceManager.GetString("VGroupName_G_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string VGroupName_G_File {
            get {
                return ResourceManager.GetString("VGroupName_G_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   フィルター に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string VGroupName_G_Filter {
            get {
                return ResourceManager.GetString("VGroupName_G_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   表示 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string VGroupName_G_View {
            get {
                return ResourceManager.GetString("VGroupName_G_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   カーソル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string VGroupName_V_Cursor {
            get {
                return ResourceManager.GetString("VGroupName_V_Cursor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   編集 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string VGroupName_V_Edit {
            get {
                return ResourceManager.GetString("VGroupName_V_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   表示 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string VGroupName_V_View {
            get {
                return ResourceManager.GetString("VGroupName_V_View", resourceCulture);
            }
        }
    }
}
